# Generated by Django 3.2.7 on 2021-12-23 17:19

from django.db import migrations, models
import django.db.models.deletion
import django_agenda.time_span
import recurrence.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True, verbose_name='Dia de Consulta')),
                ('hora_de_inicio', models.TimeField(db_index=True, verbose_name='Hora de Inicio')),
                ('hora_de_termino', models.TimeField(db_index=True, verbose_name='Hora de Termino')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='Users.usuariopaciente')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.medico')),
            ],
            options={
                'verbose_name': 'Cita Agendada',
                'verbose_name_plural': 'Citas Agedadas',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('duracion_cita', models.IntegerField(blank=True, default=60, null=True, verbose_name='Duracion de Hora en Minutos')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Users.medico')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
            },
        ),
        migrations.CreateModel(
            name='DiasDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_occurrences', to='Users.medico')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='Agenda.disponibilidad')),
            ],
            options={
                'verbose_name': 'Dia de Atención',
                'verbose_name_plural': 'Dias de Atención',
            },
        ),
        migrations.CreateModel(
            name='AgendaOcupada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('busy', models.BooleanField(db_index=True, default=False)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Users.medico')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Agenda.agendamiento')),
                ('padding_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padded_by', to='Agenda.agendaocupada')),
            ],
            options={
                'verbose_name': 'Horario Bloqueado',
                'verbose_name_plural': 'Horarios Bloqueados',
            },
            bases=(models.Model, django_agenda.time_span.AbstractTimeSpan),
        ),
    ]
