# Generated by Django 3.2.7 on 2021-12-23 00:06

from django.db import migrations, models
import django.db.models.deletion
import django_agenda.time_span
import recurrence.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='Users.usuariopaciente')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.medico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Users.medico')),
            ],
            options={
                'verbose_name_plural': 'availabilities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('busy', models.BooleanField(db_index=True, default=False)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Users.medico')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Agenda.agendamiento')),
                ('padding_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padded_by', to='Agenda.slot')),
            ],
            options={
                'verbose_name_plural': 'time slots',
                'abstract': False,
            },
            bases=(models.Model, django_agenda.time_span.AbstractTimeSpan),
        ),
        migrations.CreateModel(
            name='AvailabilityOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_occurrences', to='Users.medico')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='Agenda.availability')),
            ],
            options={
                'verbose_name': 'availability occurrence',
                'verbose_name_plural': 'availability occurrences',
                'abstract': False,
            },
        ),
    ]
