# Generated by Django 3.2.7 on 2021-12-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '__first__'),
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agenda.disponibilidad'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.medico'),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='hora_de_inicio',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='hora_de_termino',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Hora de Termino'),
        ),
    ]
