# Generated by Django 3.2.7 on 2021-12-24 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_auto_20211223_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamiento',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2021, 12, 23, 21, 27, 40, 369768), null=True),
        ),
        migrations.AlterField(
            model_name='agendamiento',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2021, 12, 23, 21, 27, 40, 369746), null=True),
        ),
    ]
