# Generated by Django 3.2.7 on 2021-12-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_auto_20211222_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='duracion_cita',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='Duracion de Hora en Minutos'),
        ),
    ]
